# Generate the Nadia report from the audited analysis, without changing observations.
wb_nadia_report <- function(result, out) {
  x <- result$prepared$audit
  model_data <- x[x$analysis_eligible, ]
  counts <- as.data.frame(table(x$exclusion_reason))
  names(counts) <- c("Disposition", "GPs")
  primary <- subset(result$results, model == "Primary baseline-adjusted")
  display <- c("outcome", "estimate", "conf.low", "conf.high", "n", "se_type", "p_holm")
  means <- dplyr::bind_rows(lapply(c("household_months", "person_months"), function(unit) {
    y <- model_data[[paste0(unit, "_2014")]]
    data.frame(
      outcome = unit, women_reserved_mean = mean(y[model_data$q13 == 1]),
      other_mean = mean(y[model_data$q13 == 0]), min = min(y), median = median(y), max = max(y)
    )
  }))
  wb_table(means, "nadia_demand_levels", out)
  influence <- utils::read.csv(file.path(out, "tabs", "nadia_demand_influence.csv"))
  ranges <- influence |>
    dplyr::group_by(model) |>
    dplyr::summarise(
      max_leverage = max(leverage), min_leave_one_out = min(estimate_without_gp),
      max_leave_one_out = max(estimate_without_gp), rank = unique(rank),
      residual_df = unique(residual_df), .groups = "drop"
    )
  wb_table(ranges, "nadia_demand_influence_summary", out)
  plot_data <- primary
  plot_data$outcome <- ifelse(grepl("household", plot_data$outcome),
    "Household-month work demand", "Person-month work demand"
  )
  dir.create(file.path(out, "figs"), showWarnings = FALSE)
  wb_plot(plot_data, "nadia_demand", out,
    "Nadia: 2013 Pradhan reservation and FY2014-15 work demand",
    "Women's-reservation association (HC2 95% interval)"
  )
  writeLines(c(
    "# Nadia: reservations and reported MNREGA work demand", "",
    "Generated by scripts/03_nadia_report.R. See nadia_pap.md, NADIA_AUDIT.md and nadia_join_contract.md.", "",
    "This is an exploratory association, not an identified causal effect of women's leadership.",
    "The outcome is reported demand for work, not employment supplied, spending or public goods delivered.", "",
    sprintf(paste(
      "The official 2013 roster has %d Pradhan offices. The source geography bridge matches %d;",
      "%d match both demand years. One singleton caste stratum is retained in the audit but excluded",
      "from models under a documented support amendment made before estimation."
    ), nrow(x), sum(x$membership_matched), sum(x$linked_complete_eligible)),
    sprintf("The analysis uses %d GPs (%d women-reserved) in %d blocks.",
      nrow(model_data), sum(model_data$q13), length(unique(model_data$block_printed))
    ), "",
    as.character(knitr::kable(counts)), "",
    "## Primary results", "",
    "Each model includes FY2012-13 demand for the same outcome, source caste category and block effects.",
    "GPs receive equal weight. Two-outcome Holm p-values accompany marginal 95% intervals.",
    "A household-month/person-month is a monthly household/person demand count summed over twelve months;",
    "it is not a unique annual household/person count and is not a person-day.", "",
    as.character(knitr::kable(primary[display], digits = 3)), "",
    "Both intervals allow sizable positive and negative associations. This does not establish no effect.", "",
    as.character(knitr::kable(means, digits = 1)), "",
    "## All planned comparisons", "",
    as.character(knitr::kable(result$results[c("model", display)], digits = 3)), "",
    "The baseline association is a selection/rotation diagnostic, not a randomization test or a causal placebo.",
    "All models use the same GPs. No outcome-based matching, trimming or winsorization is applied.", "",
    as.character(knitr::kable(result$sensitivity[c("model", display, "blocks", "df")], digits = 3)), "",
    "CR2 allows model-based dependence within administrative blocks; it does not identify the assignment unit.",
    "Coefficient-specific degrees of freedom are shown. Intervals do not account for uncertain identity links.", "",
    as.character(knitr::kable(ranges, digits = 3)), "",
    "## What this adds to quota", "",
    "This adds a separate administrative-outcome analysis using the newly recovered Nadia reservation roster.",
    "The Birbhum 1998 replication and 2003 survey analysis remain in RESULTS.md with their own units and samples.",
    "Demand years occupy wide columns. They are not pooled with the surveys or estimated as DiD.",
    "Exact block/name links do not prove unchanged boundaries or continuity of national administrative codes.",
    "Ambiguous and unmatched offices, including the source-blank Pradhan category, remain in the full 187-row ledger.",
    "Recovering historical codes and rotation histories would improve coverage and identification.",
    "Later employment and spending reports require their own measurement and design checks before analysis."
  ), file.path(out, "NADIA_RESULTS.md"))
  invisible(TRUE)
}
