# SPENDING_RESULTS.md from the estimates of 06_spending_estimate.R.

wb_spending_report <- function(estimates, module_root) {
  fmt <- function(x, digits = 2) formatC(x, format = "f", digits = digits)
  rows <- function(x) {
    paste0(
      "| ", x$model, " | ", x$outcome, " | ", fmt(x$estimate), " | [", fmt(x$conf.low), ", ",
      fmt(x$conf.high), "] | ", fmt(x$p.value, 3), " | ", fmt(x$p_holm, 3), " | ", x$n,
      " | ", fmt(x$control_mean), " |"
    )
  }
  header <- c(
    "| Model | Outcome | Estimate | 95% CI | p | p (Holm) | N | Control mean |",
    "|---|---|---:|---|---:|---:|---:|---:|"
  )
  p <- estimates$power
  w <- estimates$within
  lines <- c(
    "# West Bengal: women's Pradhan reservation and MNREGA works spending",
    "",
    "Generated by scripts/07_spending_report.R from the plan frozen in spending_pap.md",
    "(spending_plan_freeze.json). `spend` is mean annual r6 works expenditure (completed",
    "plus ongoing) over the term's fiscal years, in lakh rupees; `log_spend` is log(1 + spend).",
    "Estimates are reserved minus not reserved, within caste-quota x district-term and",
    "block x term cells, with CR2 standard errors clustered by block unless stated.",
    "",
    "## Primary", "", header, rows(estimates$primary), "",
    sprintf(
      "Minimum detectable effect on `spend` at 80%% power: %s lakh (control mean %s).",
      fmt(p$mde80[1]), fmt(estimates$primary$control_mean[1])
    ),
    "",
    "## Within GP: Nadia 2013 and 2018", "",
    sprintf("%d GPs observed in both terms; %d change reservation status.", w$gps[1], w$switching_gps[1]),
    "", header, rows(w), "",
    "## Secondary outcomes (Holm across the five)", "", header, rows(estimates$secondary), "",
    "## Sensitivity", "", header, rows(estimates$sensitivity), "",
    "## Diagnostic: previous-term spending on 2018 reservation", "",
    "Not a placebo: the roster can link 2013 and 2018 reservation.", "",
    header, rows(estimates$diagnostic), ""
  )
  writeLines(lines, file.path(module_root, "SPENDING_RESULTS.md"))
}
